/**
 * PDF Export Utilities
 * 
 * This module provides comprehensive PDF export functionality for financial data.
 * Supports exporting various types of financial reports including expenses, income,
 * budgets, and complete financial summaries.
 */

import jsPDF from 'jspdf';
import { supabase } from '@/integrations/supabase/client';

/**
 * Interface for expense data structure
 */
export interface ExpenseData {
  id: string;
  amount: number;
  category: string;
  description: string;
  date: string;
  type?: 'expense' | 'income';
}

/**
 * Interface for budget data structure
 */
export interface BudgetData {
  id: string;
  name: string;
  amount: number;
  spent: number;
  category: string;
  period: string;
}

/**
 * Interface for goal data structure
 */
export interface GoalData {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  deadline: string;
  progress: number;
}

/**
 * Interface for financial summary structure
 */
export interface FinancialSummary {
  totalIncome: number;
  totalExpenses: number;
  netIncome: number;
  topCategories: { category: string; amount: number }[];
  period: string;
}

/**
 * Helper function to add text with proper line wrapping
 */
const addTextWithWrap = (doc: jsPDF, text: string, x: number, y: number, maxWidth: number): number => {
  const lines = doc.splitTextToSize(text, maxWidth);
  doc.text(lines, x, y);
  return y + (lines.length * 5);
};

/**
 * Add professional header with FedhaSmart branding
 */
const addProfessionalHeader = (doc: jsPDF, pageWidth: number, exportType: string): void => {
  // Header background
  doc.setFillColor(59, 130, 246); // Blue color
  doc.rect(0, 0, pageWidth, 45, 'F');
  
  // FedhaSmart logo text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('FedhaSmart', 20, 20);
  
  // Tagline
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Smart Financial Tracking', 20, 28);
  
  // Report title on the right
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  const reportTitle = `${exportType.charAt(0).toUpperCase() + exportType.slice(1)} Report`;
  doc.text(reportTitle, pageWidth - 20, 20, { align: 'right' });
  
  // Generation date
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const generatedDate = `Generated: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`;
  doc.text(generatedDate, pageWidth - 20, 30, { align: 'right' });
  
  // Report ID
  const reportId = `Report ID: FR-${Date.now().toString().slice(-6)}`;
  doc.text(reportId, pageWidth - 20, 38, { align: 'right' });
  
  // Reset text color for body content
  doc.setTextColor(0, 0, 0);
  
  // Add separator line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, 48, pageWidth - 20, 48);
};

/**
 * Add footer with page numbers and app info
 */
const addFooter = (doc: jsPDF, pageWidth: number, pageHeight: number, pageNum: number): void => {
  // Footer line
  doc.setDrawColor(200, 200, 200);
  doc.line(20, pageHeight - 25, pageWidth - 20, pageHeight - 25);
  
  // Footer text
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Generated by FedhaSmart - Smart Financial Management Platform', 20, pageHeight - 15);
  doc.text(`Page ${pageNum}`, pageWidth - 20, pageHeight - 15, { align: 'right' });
  doc.text('www.fedhasmart.com', pageWidth / 2, pageHeight - 10, { align: 'center' });
};

/**
 * Add user information section
 */
const addUserInfoSection = async (doc: jsPDF, userId: string, startY: number): Promise<number> => {
  let yPosition = startY;

  // Section header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Account Information', 20, yPosition);
  yPosition += 15;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  // Basic account info
  doc.text(`User ID: ${userId.substring(0, 8)}...`, 20, yPosition);
  yPosition += 6;
  doc.text(`Report Generated: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 20, yPosition);
  yPosition += 6;
  doc.text(`Report Type: Comprehensive Financial Analysis`, 20, yPosition);
  yPosition += 6;
  doc.text(`Currency: KES (Kenyan Shilling)`, 20, yPosition);
  yPosition += 10;

  return yPosition + 10;
};

/**
 * Add executive summary section
 */
const addExecutiveSummary = async (doc: jsPDF, userId: string, startY: number, dateRange?: { from: string; to: string }): Promise<number> => {
  let yPosition = startY;

  // Section header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Executive Summary', 20, yPosition);
  yPosition += 15;

  try {
    // Get current month data
    const currentMonth = new Date();
    currentMonth.setDate(1);
    
    // Fetch summary data
    const [expensesRes, incomeRes, budgetsRes] = await Promise.all([
      supabase.from('expenses').select('amount').eq('user_id', userId).gte('date', currentMonth.toISOString().split('T')[0]),
      supabase.from('income').select('amount').eq('user_id', userId).gte('date', currentMonth.toISOString().split('T')[0]),
      supabase.from('budgets').select('limit_amount, spent_amount').eq('user_id', userId)
    ]);

    const totalExpenses = expensesRes.data?.reduce((sum, exp) => sum + Number(exp.amount), 0) || 0;
    const totalIncome = incomeRes.data?.reduce((sum, inc) => sum + Number(inc.amount), 0) || 0;
    const netIncome = totalIncome - totalExpenses;
    const totalBudget = budgetsRes.data?.reduce((sum, budget) => sum + Number(budget.limit_amount || 0), 0) || 0;

    doc.setFontSize(12);
    doc.setFont('helvetica', 'normal');
    
    // Financial overview
    doc.text(`• Total Income this month: KES ${totalIncome.toLocaleString()}`, 25, yPosition);
    yPosition += 8;
    doc.text(`• Total Expenses this month: KES ${totalExpenses.toLocaleString()}`, 25, yPosition);
    yPosition += 8;
    doc.text(`• Net Income: KES ${netIncome.toLocaleString()}`, 25, yPosition);
    yPosition += 8;
    doc.text(`• Total Budget Allocated: KES ${totalBudget.toLocaleString()}`, 25, yPosition);
    yPosition += 8;
    
    // Financial health indicator
    const savingsRate = totalIncome > 0 ? ((netIncome / totalIncome) * 100) : 0;
    let healthStatus = 'Poor';
    if (savingsRate >= 80) healthStatus = 'Excellent';
    else if (savingsRate >= 60) healthStatus = 'Good';
    else if (savingsRate >= 40) healthStatus = 'Fair';
    
    doc.text(`• Financial Health Score: ${healthStatus} (${savingsRate.toFixed(1)}% savings rate)`, 25, yPosition);
    yPosition += 15;

  } catch (error) {
    doc.text('Unable to generate executive summary', 25, yPosition);
    yPosition += 15;
  }

  return yPosition;
};

/**
 * Add financial insights and recommendations
 */
const addFinancialInsights = async (doc: jsPDF, userId: string, startY: number): Promise<number> => {
  let yPosition = startY;

  // Check if we need a new page
  if (yPosition > 250) {
    doc.addPage();
    yPosition = 20;
  }

  // Section header
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Financial Insights & Recommendations', 20, yPosition);
  yPosition += 15;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');

  // Add generic financial tips
  const insights = [
    'Track all expenses to identify spending patterns and areas for improvement.',
    'Maintain an emergency fund equivalent to 3-6 months of expenses.',
    'Review and adjust budgets monthly based on actual spending.',
    'Consider setting up automatic savings to build wealth consistently.',
    'Use FedhaSmart\'s categorization to understand where your money goes.',
    'Regular financial reviews help maintain healthy money habits.'
  ];

  insights.forEach((insight, index) => {
    const wrappedText = doc.splitTextToSize(`${index + 1}. ${insight}`, 170);
    doc.text(wrappedText, 25, yPosition);
    yPosition += wrappedText.length * 5 + 3;
  });

  yPosition += 10;

  // Add disclaimer
  doc.setFontSize(8);
  doc.setTextColor(128, 128, 128);
  doc.text('Disclaimer: This report is for informational purposes only and does not constitute financial advice.', 20, yPosition);
  doc.text('Please consult with a qualified financial advisor for personalized recommendations.', 20, yPosition + 5);

  return yPosition + 15;
};

/**
 * Helper function to add a simple table to PDF
 */
const addSimpleTable = (
  doc: jsPDF, 
  headers: string[], 
  data: string[][], 
  startY: number, 
  colWidths: number[]
): number => {
  let yPos = startY;
  const pageHeight = doc.internal.pageSize.height;
  
  // Add headers
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  let xPos = 20;
  headers.forEach((header, index) => {
    doc.text(header, xPos, yPos);
    xPos += colWidths[index];
  });
  
  // Add line under headers
  yPos += 5;
  doc.line(20, yPos, 190, yPos);
  yPos += 5;
  
  // Add data rows
  doc.setFont('helvetica', 'normal');
  data.forEach(row => {
    // Check if we need a new page
    if (yPos > pageHeight - 30) {
      doc.addPage();
      yPos = 20;
      
      // Re-add headers on new page
      doc.setFont('helvetica', 'bold');
      let headerXPos = 20;
      headers.forEach((header, index) => {
        doc.text(header, headerXPos, yPos);
        headerXPos += colWidths[index];
      });
      yPos += 10;
      doc.setFont('helvetica', 'normal');
    }
    
    xPos = 20;
    row.forEach((cell, index) => {
      const cellText = cell.length > 20 ? cell.substring(0, 20) + '...' : cell;
      doc.text(cellText, xPos, yPos);
      xPos += colWidths[index];
    });
    yPos += 8;
  });
  
  return yPos + 10;
};

/**
 * Export financial data to PDF with formatted tables and styling
 */
export const exportFinancialDataToPDF = async (
  userId: string,
  exportType: 'expenses' | 'income' | 'budgets' | 'all' = 'all',
  dateRange?: { from: string; to: string }
): Promise<void> => {
  try {
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.width;
    const pageHeight = pdf.internal.pageSize.height;
    let yPosition = 20;
    let pageNum = 1;

    // Add professional header with branding
    addProfessionalHeader(pdf, pageWidth, exportType);
    yPosition = 55;

    // Add user information section
    yPosition = await addUserInfoSection(pdf, userId, yPosition);

    // Add executive summary if exporting all data
    if (exportType === 'all') {
      yPosition = await addExecutiveSummary(pdf, userId, yPosition, dateRange);
    }

    // Export expenses if requested
    if (exportType === 'expenses' || exportType === 'all') {
      yPosition = await addExpensesToPDF(pdf, userId, yPosition, dateRange);
    }

    // Export income if requested
    if (exportType === 'income' || exportType === 'all') {
      yPosition = await addIncomeToPDF(pdf, userId, yPosition, dateRange);
    }

    // Export budgets if requested
    if (exportType === 'budgets' || exportType === 'all') {
      yPosition = await addBudgetsToPDF(pdf, userId, yPosition);
    }

    // Add financial insights and recommendations
    if (exportType === 'all') {
      yPosition = await addFinancialInsights(pdf, userId, yPosition);
    }

    // Add footer to the current page
    addFooter(pdf, pageWidth, pageHeight, 1);

    // Save PDF
    const fileName = `fedhasmart-${exportType}-report-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);

  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
};

/**
 * Add expenses data to PDF document
 */
async function addExpensesToPDF(
  pdf: jsPDF,
  userId: string,
  startY: number,
  dateRange?: { from: string; to: string }
): Promise<number> {
  let yPosition = startY;

  // Add expenses section header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Expenses', 20, yPosition);
  yPosition += 15;

  // Fetch expenses data
  let query = supabase
    .from('expenses')
    .select('*')
    .eq('user_id', userId)
    .order('date', { ascending: false });

  if (dateRange) {
    query = query.gte('date', dateRange.from).lte('date', dateRange.to);
  }

  const { data: expenses, error } = await query;

  if (error) {
    pdf.setFontSize(12);
    pdf.text('Error loading expenses data', 20, yPosition);
    return yPosition + 20;
  }

  if (!expenses || expenses.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No expenses found for the selected period', 20, yPosition);
    return yPosition + 20;
  }

  // Prepare table data
  const headers = ['Date', 'Category', 'Amount', 'Notes'];
  const colWidths = [40, 40, 30, 50];
  const tableData = expenses.map(expense => [
    new Date(expense.date).toLocaleDateString(),
    expense.category,
    `KES ${Number(expense.amount).toLocaleString()}`,
    expense.notes || '-'
  ]);

  // Add table
  yPosition = addSimpleTable(pdf, headers, tableData, yPosition, colWidths);

  // Add total
  const totalExpenses = expenses.reduce((sum, expense) => sum + Number(expense.amount), 0);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Expenses: KES ${totalExpenses.toLocaleString()}`, 20, yPosition);
  
  return yPosition + 20;
}

/**
 * Add income data to PDF document
 */
async function addIncomeToPDF(
  pdf: jsPDF,
  userId: string,
  startY: number,
  dateRange?: { from: string; to: string }
): Promise<number> {
  let yPosition = startY;

  // Add income section header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Income', 20, yPosition);
  yPosition += 15;

  // Fetch income data
  let query = supabase
    .from('income')
    .select('*')
    .eq('user_id', userId)
    .order('date', { ascending: false });

  if (dateRange) {
    query = query.gte('date', dateRange.from).lte('date', dateRange.to);
  }

  const { data: incomes, error } = await query;

  if (error) {
    pdf.setFontSize(12);
    pdf.text('Error loading income data', 20, yPosition);
    return yPosition + 20;
  }

  if (!incomes || incomes.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No income found for the selected period', 20, yPosition);
    return yPosition + 20;
  }

  // Prepare table data
  const headers = ['Date', 'Source', 'Amount', 'Notes'];
  const colWidths = [40, 40, 30, 50];
  const tableData = incomes.map(income => [
    new Date(income.date).toLocaleDateString(),
    income.source,
    `KES ${Number(income.amount).toLocaleString()}`,
    income.notes || '-'
  ]);

  // Add table
  yPosition = addSimpleTable(pdf, headers, tableData, yPosition, colWidths);

  // Add total
  const totalIncome = incomes.reduce((sum, income) => sum + Number(income.amount), 0);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Income: KES ${totalIncome.toLocaleString()}`, 20, yPosition);
  
  return yPosition + 20;
}

/**
 * Add budgets data to PDF document
 */
async function addBudgetsToPDF(
  pdf: jsPDF,
  userId: string,
  startY: number
): Promise<number> {
  let yPosition = startY;

  // Add budgets section header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Budgets', 20, yPosition);
  yPosition += 15;

  // Fetch budgets data
  const { data: budgets, error } = await supabase
    .from('budgets')
    .select('*')
    .eq('user_id', userId)
    .order('category');

  if (error) {
    pdf.setFontSize(12);
    pdf.text('Error loading budgets data', 20, yPosition);
    return yPosition + 20;
  }

  if (!budgets || budgets.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No budgets found', 20, yPosition);
    return yPosition + 20;
  }

  // Prepare table data
  const headers = ['Category', 'Budget', 'Spent', 'Remaining'];
  const colWidths = [50, 35, 35, 40];
  const tableData = budgets.map(budget => {
    const budgetAmount = Number(budget.limit_amount || 0);
    const spentAmount = Number(budget.spent_amount || 0);
    const remaining = budgetAmount - spentAmount;
    
    return [
      budget.category,
      `KES ${budgetAmount.toLocaleString()}`,
      `KES ${spentAmount.toLocaleString()}`,
      `KES ${remaining.toLocaleString()}`
    ];
  });

  // Add table
  yPosition = addSimpleTable(pdf, headers, tableData, yPosition, colWidths);

  // Add totals
  const totalBudget = budgets.reduce((sum, budget) => sum + Number(budget.limit_amount || 0), 0);
  const totalSpent = budgets.reduce((sum, budget) => sum + Number(budget.spent_amount || 0), 0);
  
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Budget: KES ${totalBudget.toLocaleString()}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Total Spent: KES ${totalSpent.toLocaleString()}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Total Remaining: KES ${(totalBudget - totalSpent).toLocaleString()}`, 20, yPosition);
  
  return yPosition + 20;
}

/**
 * Export expenses data to PDF
 */
export const exportExpensesToPDF = (expenses: ExpenseData[], title = 'Expense Report') => {
  const doc = new jsPDF();
  
  // Add title
  doc.setFontSize(20);
  doc.text(title, 20, 20);
  
  // Add date
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
  
  // Calculate totals
  const totalExpenses = expenses
    .filter(e => e.type === 'expense' || !e.type)
    .reduce((sum, expense) => sum + expense.amount, 0);
  const totalIncome = expenses
    .filter(e => e.type === 'income')
    .reduce((sum, expense) => sum + expense.amount, 0);
  
  // Add summary
  doc.text(`Total Expenses: $${totalExpenses.toFixed(2)}`, 20, 40);
  doc.text(`Total Income: $${totalIncome.toFixed(2)}`, 20, 50);
  doc.text(`Net Income: $${(totalIncome - totalExpenses).toFixed(2)}`, 20, 60);
  
  // Prepare table data
  const headers = ['Date', 'Description', 'Category', 'Amount'];
  const colWidths = [35, 50, 40, 35];
  const tableData = expenses.map(expense => [
    new Date(expense.date).toLocaleDateString(),
    expense.description,
    expense.category,
    `$${expense.amount.toFixed(2)}`
  ]);
  
  // Add table
  addSimpleTable(doc, headers, tableData, 70, colWidths);
  
  // Save the PDF
  const fileName = `${title.toLowerCase().replace(/\s+/g, '-')}-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

/**
 * Export budgets data to PDF
 */
export const exportBudgetsToPDF = (budgets: BudgetData[], title = 'Budget Report') => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text(title, 20, 20);
  
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
  
  // Calculate totals
  const totalBudget = budgets.reduce((sum, budget) => sum + budget.amount, 0);
  const totalSpent = budgets.reduce((sum, budget) => sum + budget.spent, 0);
  const remainingBudget = totalBudget - totalSpent;
  
  doc.text(`Total Budget: $${totalBudget.toFixed(2)}`, 20, 40);
  doc.text(`Total Spent: $${totalSpent.toFixed(2)}`, 20, 50);
  doc.text(`Remaining: $${remainingBudget.toFixed(2)}`, 20, 60);
  
  const headers = ['Budget Name', 'Category', 'Amount', 'Spent', 'Remaining'];
  const colWidths = [40, 30, 30, 30, 30];
  const tableData = budgets.map(budget => {
    const remaining = budget.amount - budget.spent;
    return [
      budget.name,
      budget.category,
      `$${budget.amount.toFixed(2)}`,
      `$${budget.spent.toFixed(2)}`,
      `$${remaining.toFixed(2)}`
    ];
  });
  
  addSimpleTable(doc, headers, tableData, 70, colWidths);
  
  const fileName = `budget-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

/**
 * Export financial goals data to PDF
 */
export const exportGoalsToPDF = (goals: GoalData[], title = 'Financial Goals Report') => {
  const doc = new jsPDF();
  
  doc.setFontSize(20);
  doc.text(title, 20, 20);
  
  doc.setFontSize(12);
  doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 30);
  
  const totalTargetAmount = goals.reduce((sum, goal) => sum + goal.targetAmount, 0);
  const totalCurrentAmount = goals.reduce((sum, goal) => sum + goal.currentAmount, 0);
  
  doc.text(`Total Target: $${totalTargetAmount.toFixed(2)}`, 20, 40);
  doc.text(`Total Saved: $${totalCurrentAmount.toFixed(2)}`, 20, 50);
  
  const headers = ['Goal Name', 'Target', 'Current', 'Progress'];
  const colWidths = [50, 35, 35, 40];
  const tableData = goals.map(goal => [
    goal.name,
    `$${goal.targetAmount.toFixed(2)}`,
    `$${goal.currentAmount.toFixed(2)}`,
    `${goal.progress.toFixed(1)}%`
  ]);
  
  addSimpleTable(doc, headers, tableData, 60, colWidths);
  
  const fileName = `goals-report-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

/**
 * Export comprehensive financial report
 */
export const exportComprehensiveReport = (
  expenses: ExpenseData[],
  budgets: BudgetData[],
  goals: GoalData[],
  period: string = 'Current Period'
) => {
  const doc = new jsPDF();
  
  // Title
  doc.setFontSize(20);
  doc.text('Complete Financial Report', 20, 20);
  
  doc.setFontSize(14);
  doc.text(`Period: ${period}`, 20, 35);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 45);
  
  // Financial Summary
  const totalIncome = expenses
    .filter(e => e.type === 'income')
    .reduce((sum, e) => sum + e.amount, 0);
  
  const totalExpenses = expenses
    .filter(e => e.type === 'expense' || !e.type)
    .reduce((sum, e) => sum + e.amount, 0);
  
  doc.setFontSize(16);
  doc.text('Financial Summary', 20, 60);
  
  doc.setFontSize(12);
  doc.text(`Total Income: $${totalIncome.toFixed(2)}`, 30, 75);
  doc.text(`Total Expenses: $${totalExpenses.toFixed(2)}`, 30, 85);
  doc.text(`Net Income: $${(totalIncome - totalExpenses).toFixed(2)}`, 30, 95);
  
  const fileName = `financial-summary-${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};
