/**
 * PDF Export Utilities
 * 
 * This module provides comprehensive PDF export functionality for financial data.
 * Supports exporting various types of financial reports including expenses, income,
 * budgets, and complete financial summaries.
 */

import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import { supabase } from '@/integrations/supabase/client';

/**
 * Interface for expense data structure
 */
interface ExpenseData {
  id: string;
  amount: number;
  category: string;
  date: string;
  notes?: string;
}

/**
 * Interface for income data structure
 */
interface IncomeData {
  id: string;
  amount: number;
  source: string;
  date: string;
  notes?: string;
}

/**
 * Interface for budget data structure
 */
interface BudgetData {
  id: string;
  category: string;
  amount: number;
  spent: number;
  period: string;
}

/**
 * Export financial data to PDF with formatted tables and styling
 * @param userId - User ID to fetch data for
 * @param exportType - Type of export (expenses, income, budgets, all)
 * @param dateRange - Date range filter (optional)
 * @returns Promise<void>
 */
export const exportFinancialDataToPDF = async (
  userId: string,
  exportType: 'expenses' | 'income' | 'budgets' | 'all' = 'all',
  dateRange?: { from: string; to: string }
): Promise<void> => {
  try {
    // Create new PDF document
    const pdf = new jsPDF('p', 'mm', 'a4');
    const pageWidth = pdf.internal.pageSize.width;
    const pageHeight = pdf.internal.pageSize.height;
    let yPosition = 20;

    // Add header
    pdf.setFontSize(20);
    pdf.setFont('helvetica', 'bold');
    pdf.text('Financial Report', pageWidth / 2, yPosition, { align: 'center' });
    
    yPosition += 10;
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.text(`Generated on: ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
    
    yPosition += 20;

    // Export expenses if requested
    if (exportType === 'expenses' || exportType === 'all') {
      yPosition = await addExpensesToPDF(pdf, userId, yPosition, pageHeight, dateRange);
    }

    // Export income if requested
    if (exportType === 'income' || exportType === 'all') {
      yPosition = await addIncomeToPDF(pdf, userId, yPosition, pageHeight, dateRange);
    }

    // Export budgets if requested
    if (exportType === 'budgets' || exportType === 'all') {
      yPosition = await addBudgetsToPDF(pdf, userId, yPosition, pageHeight);
    }

    // Add footer
    const totalPages = (pdf as any).internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'normal');
      pdf.text(
        `Page ${i} of ${totalPages} - Generated by FedHaSmart Finance App`,
        pageWidth / 2,
        pageHeight - 10,
        { align: 'center' }
      );
    }

    // Save PDF
    const fileName = `financial-report-${exportType}-${new Date().toISOString().split('T')[0]}.pdf`;
    pdf.save(fileName);

  } catch (error) {
    console.error('Error generating PDF:', error);
    throw new Error('Failed to generate PDF report');
  }
};

/**
 * Add expenses data to PDF document
 */
async function addExpensesToPDF(
  pdf: jsPDF,
  userId: string,
  startY: number,
  pageHeight: number,
  dateRange?: { from: string; to: string }
): Promise<number> {
  let yPosition = startY;

  // Add expenses section header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Expenses', 20, yPosition);
  yPosition += 10;

  // Fetch expenses data
  let query = supabase
    .from('expenses')
    .select('*')
    .eq('user_id', userId)
    .order('date', { ascending: false });

  if (dateRange) {
    query = query.gte('date', dateRange.from).lte('date', dateRange.to);
  }

  const { data: expenses, error } = await query;

  if (error) {
    pdf.setFontSize(12);
    pdf.text('Error loading expenses data', 20, yPosition);
    return yPosition + 20;
  }

  if (!expenses || expenses.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No expenses found for the selected period', 20, yPosition);
    return yPosition + 20;
  }

  // Add table headers
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Date', 20, yPosition);
  pdf.text('Category', 60, yPosition);
  pdf.text('Amount (KES)', 100, yPosition);
  pdf.text('Notes', 140, yPosition);
  yPosition += 5;

  // Add line under headers
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;

  // Add expense rows
  pdf.setFont('helvetica', 'normal');
  let totalExpenses = 0;

  for (const expense of expenses) {
    // Check if we need a new page
    if (yPosition > pageHeight - 30) {
      pdf.addPage();
      yPosition = 20;
    }

    pdf.text(new Date(expense.date).toLocaleDateString(), 20, yPosition);
    pdf.text(expense.category, 60, yPosition);
    pdf.text(`KES ${Number(expense.amount).toLocaleString()}`, 100, yPosition);
    pdf.text(expense.notes || '-', 140, yPosition, { maxWidth: 45 });
    
    totalExpenses += Number(expense.amount);
    yPosition += 8;
  }

  // Add total
  yPosition += 5;
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Expenses: KES ${totalExpenses.toLocaleString()}`, 20, yPosition);
  
  return yPosition + 20;
}

/**
 * Add income data to PDF document
 */
async function addIncomeToPDF(
  pdf: jsPDF,
  userId: string,
  startY: number,
  pageHeight: number,
  dateRange?: { from: string; to: string }
): Promise<number> {
  let yPosition = startY;

  // Check if we need a new page
  if (yPosition > pageHeight - 100) {
    pdf.addPage();
    yPosition = 20;
  }

  // Add income section header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Income', 20, yPosition);
  yPosition += 10;

  // Fetch income data
  let query = supabase
    .from('income')
    .select('*')
    .eq('user_id', userId)
    .order('date', { ascending: false });

  if (dateRange) {
    query = query.gte('date', dateRange.from).lte('date', dateRange.to);
  }

  const { data: incomes, error } = await query;

  if (error) {
    pdf.setFontSize(12);
    pdf.text('Error loading income data', 20, yPosition);
    return yPosition + 20;
  }

  if (!incomes || incomes.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No income found for the selected period', 20, yPosition);
    return yPosition + 20;
  }

  // Add table headers
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Date', 20, yPosition);
  pdf.text('Source', 60, yPosition);
  pdf.text('Amount (KES)', 100, yPosition);
  pdf.text('Notes', 140, yPosition);
  yPosition += 5;

  // Add line under headers
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;

  // Add income rows
  pdf.setFont('helvetica', 'normal');
  let totalIncome = 0;

  for (const income of incomes) {
    // Check if we need a new page
    if (yPosition > pageHeight - 30) {
      pdf.addPage();
      yPosition = 20;
    }

    pdf.text(new Date(income.date).toLocaleDateString(), 20, yPosition);
    pdf.text(income.source, 60, yPosition);
    pdf.text(`KES ${Number(income.amount).toLocaleString()}`, 100, yPosition);
    pdf.text(income.notes || '-', 140, yPosition, { maxWidth: 45 });
    
    totalIncome += Number(income.amount);
    yPosition += 8;
  }

  // Add total
  yPosition += 5;
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Income: KES ${totalIncome.toLocaleString()}`, 20, yPosition);
  
  return yPosition + 20;
}

/**
 * Add budgets data to PDF document
 */
async function addBudgetsToPDF(
  pdf: jsPDF,
  userId: string,
  startY: number,
  pageHeight: number
): Promise<number> {
  let yPosition = startY;

  // Check if we need a new page
  if (yPosition > pageHeight - 100) {
    pdf.addPage();
    yPosition = 20;
  }

  // Add budgets section header
  pdf.setFontSize(16);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Budgets', 20, yPosition);
  yPosition += 10;

  // Fetch budgets data
  const { data: budgets, error } = await supabase
    .from('budgets')
    .select('*')
    .eq('user_id', userId)
    .order('category');

  if (error) {
    pdf.setFontSize(12);
    pdf.text('Error loading budgets data', 20, yPosition);
    return yPosition + 20;
  }

  if (!budgets || budgets.length === 0) {
    pdf.setFontSize(12);
    pdf.text('No budgets found', 20, yPosition);
    return yPosition + 20;
  }

  // Add table headers
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Category', 20, yPosition);
  pdf.text('Budget (KES)', 70, yPosition);
  pdf.text('Spent (KES)', 110, yPosition);
  pdf.text('Remaining (KES)', 150, yPosition);
  yPosition += 5;

  // Add line under headers
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;

  // Add budget rows
  pdf.setFont('helvetica', 'normal');
  let totalBudget = 0;
  let totalSpent = 0;

  for (const budget of budgets) {
    // Check if we need a new page
    if (yPosition > pageHeight - 30) {
      pdf.addPage();
      yPosition = 20;
    }

    const budgetAmount = Number(budget.limit_amount);
    const spentAmount = Number(budget.spent_amount || 0);
    const remaining = budgetAmount - spentAmount;

    pdf.text(budget.category, 20, yPosition);
    pdf.text(budgetAmount.toLocaleString(), 70, yPosition);
    pdf.text(spentAmount.toLocaleString(), 110, yPosition);
    pdf.text(remaining.toLocaleString(), 150, yPosition);
    
    totalBudget += budgetAmount;
    totalSpent += spentAmount;
    yPosition += 8;
  }

  // Add totals
  yPosition += 5;
  pdf.line(20, yPosition, 190, yPosition);
  yPosition += 5;
  pdf.setFont('helvetica', 'bold');
  pdf.text(`Total Budget: KES ${totalBudget.toLocaleString()}`, 20, yPosition);
  yPosition += 5;
  pdf.text(`Total Spent: KES ${totalSpent.toLocaleString()}`, 20, yPosition);
  yPosition += 5;
  pdf.text(`Total Remaining: KES ${(totalBudget - totalSpent).toLocaleString()}`, 20, yPosition);
  
  return yPosition + 20;
}

/**
 * Export specific page content as PDF using html2canvas
 * @param elementId - ID of the element to export
 * @param filename - Name of the PDF file
 */
export const exportElementToPDF = async (elementId: string, filename: string): Promise<void> => {
  try {
    const element = document.getElementById(elementId);
    if (!element) {
      throw new Error(`Element with ID "${elementId}" not found`);
    }

    // Create canvas from element
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      logging: false,
    });

    // Create PDF
    const pdf = new jsPDF('p', 'mm', 'a4');
    const imgData = canvas.toDataURL('image/png');
    
    const pdfWidth = pdf.internal.pageSize.getWidth() - 20; // 10mm margin on each side
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 10, 10, pdfWidth, pdfHeight);
    pdf.save(filename);

  } catch (error) {
    console.error('Error exporting element to PDF:', error);
    throw new Error('Failed to export content to PDF');
  }
};
